### PR TITLE
pyxis: Add init script for make difference between MI CC 9 and MI 9 Lite

### PR DESCRIPTION
**Pull request by Mashopy**
Thanks to @TheScarastic for the initial init script

### CODE REVIEW

**Comment by ivecera** [comment]
Hmm, why do you use fingerprint "google/walleye/walleye:8.1.0/OPM1.171019.011/4448085:user/release-keys" ???

**Comment by Mashopy** [comment]
> Hmm, why do you use fingerprint "google/walleye/walleye:8.1.0/OPM1.171019.011/4448085:user/release-keys" ???

For pass safetynet because now all device who doesn't have a build fingerprint from may 2019 or before can't pass safetynet on custom rom

**Comment by ivecera** [comment]
Hmm, wouldn't it be better to use some Xiaomi's official fingerprint for Mi 9 Lite?

**Comment by Mashopy** [comment]
> Hmm, wouldn't it be better to use some Xiaomi's official fingerprint for Mi 9 Lite?

Already tried, doesn't pass safetynet

**Comment by ivecera** [comment]
OK, thanks for answer :-).

**Pull request merged**
